### ISSUE TITLE
without UPnP support?

### ISSUE THREAD

**Issue by jasonliul** [minnyres/amule-win32#1]
There is such a setting, but can not enable it.

also, campare with eMule, luck of some feature
- close button also can minimizes the window to the tray
- file extension columns in the search results

**Comment by minnyres** [comment]
Hi, UPnP is disabled because of cross compiling. I will consider to support it in the future.
As for the lack of features, you can post a feature request at https://github.com/amule-project/amule/issues.

**Comment by jasonliul** [comment]
Thanks pal.

**Comment by minnyres** [comment]
UPnP is supported in [release v2.3.3.2](https://github.com/minnyres/amule-win32/releases/tag/v2.3.3.2)

**Comment by exaghost** [comment]
Hi!
How can I help with better UPnP support? I see the known issue with some cases it's broken. :( Also for me.....

`!2023-04-24` 14:22:46: Universal Plug and Play: Internet Gateway Device Detected.
!2023-04-24 14:22:46: Universal Plug and Play: WAN Service Detected: 'urn:schemas-upnp-org:service:WANIPConnection:1'.
!2023-04-24 14:22:46: Universal Plug and Play: Internet Gateway Device Detected.
!2023-04-24 14:22:46: Universal Plug and Play: Successfully retrieved SCPD Document for service urn:schemas-upnp-org:service:WANIPConnection:1, absEventSubURL: http://192.168.1.12:1900/ipc.
!2023-04-24 14:22:46: Universal Plug and Play: Internet Gateway Device Detected.
!2023-04-24 14:22:46: Universal Plug and Play: Internet Gateway Device Detected.
!2023-04-24 14:22:46: Universal Plug and Play: Successfully subscribed to service urn:schemas-upnp-org:service:WANIPConnection:1, absEventSubURL: http://192.168.1.12:1900/ipc.
!2023-04-24 14:22:46: Universal Plug and Play: Uninteresting service detected: 'urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1'. Ignoring.
!2023-04-24 14:22:46: Universal Plug and Play: Uninteresting service detected: 'urn:schemas-wifialliance-org:service:WFAWLANConfig:1'. Ignoring.
!2023-04-24 14:22:46: Universal Plug and Play: Uninteresting service detected: 'urn:schemas-upnp-org:service:Layer3Forwarding:1'. Ignoring.
!2023-04-24 14:22:46: Universal Plug and Play: UPNP_EVENT_RECEIVED:
!2023-04-24 14:22:46:     SID: uuid:412b7116-e299-11ed-8b47-c58de3a7eaa2
!2023-04-24 14:22:46:     Key: 0
!2023-04-24 14:22:46:     Property list:
!2023-04-24 14:22:46:         ConnectionType='IP_Routed'
!2023-04-24 14:22:46:         PossibleConnectionTypes='IP_Routed'
!2023-04-24 14:22:46:         ConnectionStatus='Connected'
!2023-04-24 14:22:46:         Uptime='12 Days, 19:37:18'
!2023-04-24 14:22:46:         LastConnectionError='ERROR_NONE'
!2023-04-24 14:22:46:         RSIPAvailable='0'
!2023-04-24 14:22:46:         NATEnabled='1'
!2023-04-24 14:22:46:         ExternalIPAddress='0.0.0.0'
!2023-04-24 14:22:46:         PortMappingNumberOfEntries='6'

[....]
!2023-04-24 14:22:46: Universal Plug and Play: error(UPNP_DISCOVERY_ADVERTISEMENT_ALIVE): Error retrieving device description from http://192.168.0.9:1900/igd.xml: UPNP_E_SOCKET_CONNECT(-204).
!2023-04-24 14:22:46: Universal Plug and Play: error(UPNP_DISCOVERY_ADVERTISEMENT_ALIVE): Error retrieving device description from http://192.168.0.9:1900/igd.xml: UPNP_E_SOCKET_CONNECT(-204).
!2023-04-24 14:22:46: Universal Plug and Play: error(UPNP_DISCOVERY_ADVERTISEMENT_ALIVE): Error retrieving device description from http://192.168.0.9:1900/igd.xml: UPNP_E_SOCKET_CONNECT(-204).

(MORE SAME LINES)

!2023-04-24 14:22:47: Universal Plug and Play: error(UPNP_DISCOVERY_ADVERTISEMENT_ALIVE): Error retrieving device description from http://192.168.0.9:1900/igd.xml: UPNP_E_SOCKET_CONNECT(-204).
!2023-04-24 14:22:47: Universal Plug and Play: error(UPNP_DISCOVERY_ADVERTISEMENT_ALIVE): Error retrieving device description from http://192.168.0.9:49152/wps_device.xml: UPNP_E_SOCKET_CONNECT(-204).
!2023-04-24 14:22:47: Universal Plug and Play: error(UPNP_DISCOVERY_ADVERTISEMENT_ALIVE): Error retrieving device description from http://192.168.0.9:49152/wps_device.xml: UPNP_E_SOCKET_CONNECT(-204).
!2023-04-24 14:22:47: Universal Plug and Play: error(UPNP_DISCOVERY_ADVERTISEMENT_ALIVE): Error retrieving device description from http://192.168.0.9:49152/wps_device.xml: UPNP_E_SOCKET_CONNECT(-204).
!2023-04-24 14:22:47: Universal Plug and Play: error(UPNP_DISCOVERY_ADVERTISEMENT_ALIVE): Error retrieving device description from http://192.168.0.9:49152/wps_device.xml: UPNP_E_SOCKET_CONNECT(-204).
!2023-04-24 14:22:47: Universal Plug and Play: error(UPNP_DISCOVERY_ADVERTISEMENT_ALIVE): Error retrieving device description from http://192.168.0.9:49152/wps_device.xml: UPNP_E_SOCKET_CONNECT(-204).
!2023-04-24 14:22:47: Universal Plug and Play: error(UPNP_DISCOVERY_ADVERTISEMENT_ALIVE): Error retrieving device description from http://192.168.0.9:49152/wps_device.xml: UPNP_E_SOCKET_CONNECT(-204).
!2023-04-24 14:22:47: Universal Plug and Play: error(UPNP_DISCOVERY_ADVERTISEMENT_ALIVE): Error retrieving device description from http://192.168.0.9:49152/wps_device.xml: UPNP_E_SOCKET_CONNECT(-204).
!2023-04-24 14:22:47: Universal Plug and Play: error(UPNP_DISCOVERY_ADVERTISEMENT_ALIVE): Error retrieving device description from http://192.168.0.9:49152/wps_device.xml: UPNP_E_SOCKET_CONNECT(-204).
!2023-04-24 14:22:47: Universal Plug and Play: error(UPNP_DISCOVERY_ADVERTISEMENT_ALIVE): Error retrieving device description from http://192.168.0.9:1900/igd.xml: UPNP_E_SOCKET_CONNECT(-204).

(MORE LINES)

!2023-04-24 15:11:54: Universal Plug and Play: error(UPNP_DISCOVERY_ADVERTISEMENT_ALIVE): Error retrieving device description from http://192.168.0.9:1900/igd.xml: UPNP_E_SOCKET_CONNECT(-204).
!2023-04-24 15:11:58: Universal Plug and Play: UPNP_EVENT_AUTORENEWAL_FAILED: Re-subscribed to EventURL 'http://192.168.1.12:1900/ipc' with SID == 'uuid:97aa36d8-e2a1-11ed-8b47-c58de3a7eaa2'.
!2023-04-24 15:11:58: Universal Plug and Play: UPNP_EVENT_RECEIVED:
!2023-04-24 15:11:58:     SID: uuid:97aa36d8-e2a1-11ed-8b47-c58de3a7eaa2
!2023-04-24 15:11:58:     Key: 0
!2023-04-24 15:11:58:     Property list:
!2023-04-24 15:11:58:         ConnectionType='IP_Routed'
!2023-04-24 15:11:58:         PossibleConnectionTypes='IP_Routed'
!2023-04-24 15:11:58:         ConnectionStatus='Connected'
!2023-04-24 15:11:58:         Uptime='9 Days, 22:18:59'
!2023-04-24 15:11:58:         LastConnectionError='ERROR_NONE'
!2023-04-24 15:11:58:         RSIPAvailable='0'
!2023-04-24 15:11:58:         NATEnabled='1'
!2023-04-24 15:11:58:         ExternalIPAddress='0.0.0.0'
!2023-04-24 15:11:58:         PortMappingNumberOfEntries='0'
!2023-04-24 15:12:01: Universal Plug and Play: error(UPNP_DISCOVERY_ADVERTISEMENT_ALIVE): Error retrieving device description from http://192.168.0.9:1900/igd.xml: UPNP_E_SOCKET_CONNECT(-204).

(MORE LINES)

!2023-04-24 15:20:28: Universal Plug and Play: error(UPNP_DISCOVERY_ADVERTISEMENT_ALIVE): Error retrieving device description from http://192.168.0.9:1900/igd.xml: UPNP_E_SOCKET_CONNECT(-204).
!2023-04-24 15:20:29: Universal Plug and Play: error(UPNP_DISCOVERY_ADVERTISEMENT_ALIVE): Error retrieving device description from http://192.168.0.9:1900/igd.xml: UPNP_E_SOCKET_CONNECT(-204).
!2023-04-24 15:20:29: Universal Plug and Play: error(UPNP_DISCOVERY_ADVERTISEMENT_ALIVE): Error retrieving device description from http://192.168.0.9:49152/wps_device.xml: UPNP_E_SOCKET_CONNECT(-204).
!2023-04-24 15:20:29: Universal Plug and Play: error(UPNP_DISCOVERY_ADVERTISEMENT_ALIVE): Error retrieving device description from http://192.168.0.9:49152/wps_device.xml: UPNP_E_SOCKET_CONNECT(-204).
!2023-04-24 15:20:29: Universal Plug and Play: error(UPNP_DISCOVERY_ADVERTISEMENT_ALIVE): Error retrieving device description from http://192.168.0.9:49152/wps_device.xml: UPNP_E_SOCKET_CONNECT(-204).
!2023-04-24 15:20:29: Universal Plug and Play: error(UPNP_DISCOVERY_ADVERTISEMENT_ALIVE): Error retrieving device description from http://192.168.0.9:49152/wps_device.xml: UPNP_E_SOCKET_CONNECT(-204).
!2023-04-24 15:20:29: Universal Plug and Play: error(UPNP_DISCOVERY_ADVERTISEMENT_ALIVE): Error retrieving device description from http://192.168.0.9:49152/wps_device.xml: UPNP_E_SOCKET_CONNECT(-204).
!2023-04-24 15:20:30: Universal Plug and Play: error(UPNP_DISCOVERY_ADVERTISEMENT_ALIVE): Error retrieving device description from http://192.168.0.9:49152/wps_device.xml: UPNP_E_SOCKET_CONNECT(-204).
!2023-04-24 15:20:32: Universal Plug and Play: error(UPNP_DISCOVERY_ADVERTISEMENT_ALIVE): Error retrieving device description from http://192.168.0.9:49152/wps_device.xml: UPNP_E_SOCKET_CONNECT(-204).
!2023-04-24 15:20:35: Universal Plug and Play: error(UPNP_DISCOVERY_ADVERTISEMENT_ALIVE): Error retrieving device description from http://192.168.0.9:49152/wps_device.xml: UPNP_E_SOCKET_CONNECT(-204).
!2023-04-24 15:20:43: Universal Plug and Play: error(UPNP_DISCOVERY_ADVERTISEMENT_ALIVE): Error retrieving device description from http://192.168.0.9:1900/igd.xml: UPNP_E_SOCKET_CONNECT(-204).
!2023-04-24 15:20:48: Universal Plug and Play: error(UPNP_DISCOVERY_ADVERTISEMENT_ALIVE): Error retrieving device description from http://192.168.0.9:1900/igd.xml: `UPNP_E_SOCKET_CONNECT(-204).`

I can open a new ticket if it helps.... Unfurtunetelly, I don not have access to router configuration. (That's why I need UPnP...)

**Comment by minnyres** [comment]
@exaghost I cannot help test upnp since upnp on my router seems broken. I would suggest you first check the upnp function of your router, by testing with other software such as qbittorrent.

**Comment by exaghost** [comment]
> @exaghost I cannot help test upnp since upnp on my router seems broken. I would suggest you first check the upnp function of your router, by testing with other software such as qbittorrent.

Hi!
Oh, my bad. Yes, qBittorrent works just fine in the same network environment. Automatic mapping and incoming connections are okay.

**Comment by minnyres** [comment]
The error `UPNP_E_SOCKET_CONNECT` means that an error occurred connecting to the url. What is the IP address of the router? It looks that the device is in two networks `192.168.1.x` and `192.168.0.x`

**Comment by minnyres** [comment]
Hi @exaghost Is the UPnP error fixed now?
